services:
  - type: web
    name: complaintsys
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn complaintsys.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - fromDatabase:
          name: complaint-db
          property: connectionString

databases:
  - name: complaint-db
    databaseName: complaint_db
    user: complaintuser
